### ISSUE TITLE
Issue with Column Name

### ISSUE THREAD

**Issue by EvaMartinuzzi** [laserlemon/periscope#10]
When a column name is 'open', it is unable to be used by periscope and needs to be renamed.  The issue I get is `Errno::ENOENT: No such file or directory @ rb_sysopen - 1`

**Comment by laserlemon** [comment]
Yeah, `open` is a tricky column/method name to use. It comes up for me when searching for reserved words in Rails. Sorry I can't be more help, but my suggestion would be to avoid `open` as a column name. See: https://reservedwords.herokuapp.com/words/open
