### ISSUE TITLE
Support for Rails 5.1

### ISSUE THREAD

**Issue by lephyrius** [laserlemon/periscope#13]
I get this error when doing the bundle:
```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activerecord (~> 5.1.0)

    periscope-activerecord (~> 2.1.1) was resolved to 2.1.1, which depends on
      activerecord (< 5.1, >= 3)
```

**Comment by dja** [comment]
@laserlemon Is this an easy fix?

**Comment by laserlemon** [comment]
Thank you and sorry for the slow response. I wouldn't call it _easy_ but it's in progress at #14. Please take a look! As soon as the Travis build agrees that everything is :green_heart:, I'll merge and cut new releases of `periscope-activerecord` and `periscope-mongoid`. Thank you! 👏
