### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by jdalt** [laserlemon/periscope#8]
Does this gem support Rails 5? I tried using `periscope-activerecord` with Rails 5 and got:
```undefined local variable or method `scoped' for $MODEL_NAME```

Looks like this line is probably causing that:
https://github.com/laserlemon/periscope/blob/master/lib/periscope/adapters/active_record.rb#L12
```
def periscope_default_scope
  ::ActiveRecord::VERSION::MAJOR == 4 ? all : scoped
end
```
Updating a local copy of the gem worked for me. I opened a PR to update this: https://github.com/laserlemon/periscope/pull/9

**Comment by laserlemon** [comment]
It does now, thank you!
